### ISSUE TITLE
Interaction 

### ISSUE THREAD

**Issue by davidvilanova** [FrederickHuangLin/ANCOM-Code-Archive#25]
Hi,
In the exemple dataset from your tutorial it seems that it is not currently possible to use the interaction of two factors.
So for instance use `formular="age + nation*bmi_group" `instead of f`ormular="age + nation +bmi_group"`

```
out = ancombc(phyloseq = phylum_data, formula = "age + nation * bmi_group", 
+               p_adj_method = "holm", zero_cut = 0.90, lib_cut = 1000, 
+               group = "nation", struc_zero = TRUE, neg_lb = TRUE, tol = 1e-5, 
+               max_iter = 100, conserve = TRUE, alpha = 0.05, global = TRUE)
Error in vapply(seq(n_taxa), function(i) dnorm(Delta[i], delta, sqrt(nu0[i])),  : 
  values must be length 1,
 but FUN(X[[2]]) result is length 0
In addition: Warning message:
In sqrt(nu0[i]) : NaNs produced
```
Would be a great feature to have.

**Comment by FrederickHuangLin** [comment]
Hi @davidvilanova,

Thanks for catching this! Theoretically, the ANCOM-BC model should be able to handle the interaction terms, the error message must be due to some computational problems. Your report has been recorded and I will keep you posted about the future update of the package.

Again, I greatly appreciate your help in making ANCOMBC package better!

Best,
Huang

**Comment by miguensblanco** [comment]
Following up from this issue:

I have beent trying to run a main variable with a nested/interaction effect but I keep getting erros such as "column Responder * Timepoint2 cannot be found" or "Error in Timepoint2 + Timepoint2 : non-numeric argument to binary operator". 

My code is:

`main_var = "Responder * Timepoint2"; p_adj_method = "BH"; alpha = 0.05
adj_formula = c("Timepoint2","Sex","Age","Invasive_infection_preFMT", "Underlying.condition", "Bowel_cleansing"); rand_formula = c("~ 1 | Subject_ID", "~ 1 | Donor","~ 1 | Country")
res = ANCOM(feature_table, meta_data, struc_zero, main_var, p_adj_method, 
            alpha, adj_formula, rand_formula)
`

I would like to know if I am using the wrong syntax and which one would be the right one

Thanks in advance :)

Jesus

**Comment by FrederickHuangLin** [comment]
Hi @miguensblanco,

The `adj_formula` should be specified as `"Timepoint2 + Sex + Age + Invasive_infection_preFMT + Underlying.condition + Bowel_cleansing"` instead of `c("Timepoint2","Sex","Age","Invasive_infection_preFMT", "Underlying.condition", "Bowel_cleansing")` and `rand_formula` you specified are nested random effects, which the current version of ANCOM does not support it, unfortunately. You can try `rand_formula = "~ 1 | Subject_ID"` for single random subject effect.

Best,
Huang

**Comment by madbullahi** [comment]
Hi Huang, 
Just a quick question. Does the latest version of ancom support nested random effect? If not, do you have any suggestions on how to go about this? Thank you

**Comment by FrederickHuangLin** [comment]
Hi @madbullahi,

Thanks for your question! 

`ancom` leverages the `nlme` R package for specifying random effects. For a random formula with nested random effects, you can check this [post](https://stackoverflow.com/questions/16452233/how-to-model-nested-random-effect-in-nlme-package).

Please note that this repository is no longer maintained. For the most up-to-date information about `ancom`, please go to the [ANCOMBC](https://github.com/FrederickHuangLin/ANCOMBC) repository.

Best,
Huang
