### ISSUE TITLE
Running ANCOM in different batches

### ISSUE THREAD

**Issue by miguensblanco** [FrederickHuangLin/ANCOM-Code-Archive#38]
Dear all,

Thanks for this great too.

I needed to run ANCOM for whole genome sequencing for 4000 strains and 131 samples. So, I was willing to run this trough our server but again and again I was having the follow error:` Error: protect(): protection stack overflow`

I tried modifying the `max-ppsize=500000` to its maximum value but again, sooner or later runnning into the same issue.

I then ran the strains in batches. The smalles amount of samples that I was able to run was 500. So it took me 9 runs to finish the analysis. However, when I finished and assembled my data I realize that the W values is always related to the amount of hypothesis ran per batch, so no W would be above 500 since it is the number of strains per batch. Is that ok in terms of statistics? Have any suggestion about how to run these type of data sets?

Any tip would be great :)

Thanks,

Jesus

**Comment by sniban** [comment]
Hello all, 
I am also getting the same error "Error: protect(): protection stack overflow" for microbiome data which have about 380 samples collected longitudinally from 5 treatment groups. I am trying to get deferentially abundant features between these groups.
I keep getting the same error even if on running the code in university HPC, and allocating high memory for this analysis. 
Could this error be because I am trying to compare 5 groups and 6 time points, which is too much!
Any suggestion would be great to help me to troubleshoot this error and complete the analysis. 

Thank you.
Sunil

**Comment by FrederickHuangLin** [comment]
Hi @miguensblanco and @sniban,

Thanks for your questions!

First of all, it seems the error message your encountered `Error: protect(): protection stack overflow` is not related to the ANCOM function. I searched a bit and think this [post](https://stackoverflow.com/questions/32826906/how-to-solve-protection-stack-overflow-issue-in-r-studio) might be helpful.

Also, for your question @miguensblanco about running ANCOM in batches; yes, you are right. The W statistic returned by ANCOM is related to the number of taxa since it depends on the number of comparisons which is `# taxa - 1`.

I understand that running 4000 strains altogether might take a long time. Will the pre-processing step help? Usually, the abundance table is very sparse, and setting `zero_cut = 0.90` in the pre-processing step will discard most taxa.

Best,
Huang

**Comment by FrederickHuangLin** [comment]
Hi @miguensblanco and @sniban,

I am happy to share with you that `ancom` function has been merged and published in our [ANCOMBC](https://www.bioconductor.org/packages/release/bioc/html/ANCOMBC.html) R package, which now supports parallel computing. 

Please feel free to test it out and any feedback is highly appreciated!

Best,
Huang
