### ISSUE TITLE
Input pre-processed data

### ISSUE THREAD

**Issue by kennyyeo13** [FrederickHuangLin/ANCOM-Code-Archive#49]
Hi Frederick, 

I was wondering if it would make sense to use a pre-processed CLR transformed data for ANCOM?

I batched-adjusted a few dataset and the dataset is currently CLR-transformed. I then used microbiomeMarker R package which have ANCOM function. However, because my data is already CLR-transformed, i did not transform it again and ran the ANCOM function. I want to compare the differences between groups, therefore I ran ANCOM.

I was able to get the W values. But I am not sure of this data is okay to use?

Thanks
Kenny

**Comment by FrederickHuangLin** [comment]
Hi @kennyyeo13,

Unfortunately, I don't think you can run ANCOM with CLR-transformed data. Because ANCOM methodology involves an ALR transformation of the raw data, performing ANCOM on CLR-transformed data leads to double transformation and will change the result.

Also, please be aware that this repository is no longer maintained. For questions or bug reports, please go to our [ANCOMBC](https://github.com/FrederickHuangLin/ANCOMBC) repository.

Best,
Frederick
